### ISSUE TITLE
Many problems to start the experiments

### ISSUE THREAD

**Issue by Ripper346** [claying/GCKN#6]
I have the same error of #4 when launching the unsupervised experiment plus others. I am running the code inside a docker container so is very fresh. This is the dockerfile
```dockerfile
FROM continuumio/miniconda3 AS miniconda
RUN conda create -n py36 python=3.6 \
    && apt-get update && apt-get install -y --no-install-recommends make gcc g++ \
    && conda install -n py36 -c pytorch \
    numpy=1.18.5 \
    scikit-learn=0.21.3 \
    pytorch=1.3.1=py3.6_cuda10.1.243_cudnn7.6.3_0 \
    pandas=1.0.3 \
    networkx=2.4 \
    Cython=0.29.8 \
    matplotlib=3.2.2 \
    && conda run -n py36 pip3 install cyanure-mkl==0.21.post5
ENV PATH=/opt/conda/envs/py36/bin:$PATH
COPY ./ /gckn_lib
WORKDIR /gckn_lib
RUN make


FROM nvidia/cuda:11.7.0-runtime-ubuntu22.04
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
COPY --from=miniconda /opt/conda/envs/py36 /opt/conda/envs/py36
COPY --from=miniconda /gckn_lib/build /gckn_lib/build
ENV PATH=/opt/conda/envs/py36/bin:$PATH
```
The first thing is that following the readme it seems that the library is only compiled and not installed in the python conda env. In order to avoid #4 I changed the makefile into
```makefile
all:
	python setup.py build_ext --inplace
	python setup_torch.py build_ext --inplace
	python setup.py install
	python setup_torch.py install
```
At this point I can import `gckn` but I have the error
```
Traceback (most recent call last):
  File "main_unsup.py", line 6, in <module>
    from gckn.models import GCKNetFeature
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/UNKNOWN-0.0.0-py3.6-linux-x86_64.egg/gckn/models.py", line 4, in <module>
    from .layers import PathLayer, NodePooling, Linear
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/UNKNOWN-0.0.0-py3.6-linux-x86_64.egg/gckn/layers.py", line 9, in <module>
    from .dynamic_pooling.pooling import dpooling
ModuleNotFoundError: No module named 'gckn.dynamic_pooling.pooling'
```

~~If I extract in the parent file the experiments it goes ahead of that error raising the error that it can't find `from sklearn.linear_model.base` (gckn/layers.py r14) avoidable changing it into `_base`.~~ Edit: sklearn version 0.21.3 seems to have working `base`. Note that in the dockerfile I specified the versions of the package that were out by March 2020 (the penultimate commit of this repo) to avoid compatibility problems and I still had to wrote it.

So, after changing the sklearn import, the next problem is that the dataset folder isn't in the parent folder, I stopped there. I ended that it must miss something in the readme, or in the makefile, or in one setup, I don't know, I have never used cython and I am starting from a completely virgin environment, so I don't have strange things installed, it is not possible that I have to touch so much code to run it

**Comment by Ripper346** [comment]
Sorry, didn't see in readme the `export PYTHONPATH=$PWD:$PYTHONPATH`. I suggest to change the list of the packages with the versions I put in the first post so anyone can easily run the code
